### ISSUE TITLE
update to lodash 4 now causes webpack-config-merger to not merge correctly

### ISSUE THREAD

**Issue by bdefore** [huston007/webpack-config-merger#3]
I'm noticing some duplication of items that had previously (in 0.0.3) been merged properly. Here's an output of running with 0.0.4: https://gist.github.com/bdefore/547a9e18c773af5965e9 ... notice module.resolve.extensions and module.resolve.modulesDirectories (I am using webpack-config-merger to merge several times).

**Comment by huston007** [comment]
Thank you for the report. 
I can't reproduce this because it isn't clear what is incoming data and how do you merge it several times. It would be easier to fix if you provide more data and, hopefully, minimal configs to reproduce.

I tried to add this test and it doesn't work on both 0.0.3 and 0.0.4:
```
  it('should join duplicates in arrays', function() {
    firstConfig.list = ['foo', 'bar'];
    secondConfig.list = ['bar'];

    expect(merger(firstConfig, secondConfig).list)
      .toEqual(['foo', 'bar']);
  });
```

**Comment by huston007** [comment]
@bdefore okay I got this issue too with my codebase

**Comment by huston007** [comment]
There is a test which fails on new lodash
```
  it('should correct merge arrays sub property', function() {
    firstConfig.prop = {
      list: ['foo']
    };

    secondConfig.prop = {
      list: ['bar']
    };

    expect(merger(firstConfig, secondConfig).prop.list)
      .toEqual(['foo', 'bar']);
  });
```

Test got this on lodash 4: `Expected [ 'foo', 'foo', 'bar' ] to equal [ 'foo', 'bar' ].`

**Comment by huston007** [comment]
0.0.5 fixes that, please try.
